# Generated by Django 4.2.7 on 2023-11-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231116_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(default=56, max_length=200),
            preserve_default=False,
        ),
    ]
