# Generated by Django 4.2.7 on 2023-11-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_code_created_at_package_created_at_and_more'),
        ('users', '0007_remove_user_tg_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
