# Generated by Django 5.0.1 on 2024-01-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_added_to_group_user_is_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='added_to_group',
            new_name='group_member',
        ),
    ]
