# Generated by Django 5.0.1 on 2024-01-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_added_to_group_user_group_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_member',
            new_name='is_admin',
        ),
    ]
