# Generated by Django 4.2.1 on 2024-02-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_order_extra_order_status_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'admin': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='users.user'),
        ),
        migrations.AddField(
            model_name='report',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Done', 'DONE'), ('In Progress', 'IN PROGRESS'), ('Not Started', 'NOT STARTED'), ('Have Problems', 'HAVE PROBLEMS')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(limit_choices_to={'admin': True}, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='users.user'),
        ),
    ]
