# Generated by Django 4.2.7 on 2024-09-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_free_spend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='spent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
