# Generated by Django 4.2.7 on 2024-09-05 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_creditpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
    ]
