# Generated by Django 4.2.7 on 2023-11-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.TextField(),
        ),
    ]
